Fix: RegionSelector onChange error
The `control._fields[name]?._f.onChange` function in `RegionSelector.tsx` is causing a TypeError because it is not a function.  This commit aims to resolve this error.